// Auto-generated by Portfolio Generator SaaS
// Edit this file to customise your portfolio data

export interface NavItem { label: string; targetId: string; }
export interface ExpertiseItem {
  id: string; num: string; name: string; desc: string;
  type: "dna" | "neural" | "mandala" | "network" | "atom" | "spectrum";
}
export interface ProjectItem {
  id: string; num: string; cat: string; flip: boolean;
  titlePrefix: string; titleHighlight: string; titleSuffix?: string;
  img: string; desc: string; tech: string[]; link: string;
}
export interface TrainingItem { title: string; org: string; desc: string; active: boolean; }
export interface HackathonItem { name: string; date: string; desc: string; }
export interface StatItem { n: string; l: string; }
export interface SocialLink { label: string; url: string; isDownload?: boolean; }
export interface CustomSectionItem { id: string; heading: string; subheading?: string; body?: string; icon?: string; url?: string; }
export interface CustomSection { id: string; type: string; title: string; visible: boolean; items: CustomSectionItem[]; }

export const portfolioData = {
  backgroundAnimation: "dna",
  colorPalette: "neon-lime",
  customAccentColor: "",
  personal: {
  "name": "aziz said",
  "firstName": "AZIZ",
  "lastName": "SAID",
  "logoText": "AS",
  "role": "Full Stack",
  "availabilityText": "Open to Work",
  "tagline": "Portfolio — 2025 / 2026",
  "education": "Esprit",
  "heroDescription": "Crafting intelligent, scalable digital systems.",
  "heroSubTextLine1": "Full-Stack Developer crafting",
  "heroSubTextLine2": "hii",
  "primaryCtaText": "View Work",
  "secondaryCtaText": "Let's Talk",
  "scrollText": "Scroll",
  "email": "amir12.amir0011@gmail.com",
  "photoUrl": "",
  "photoPosition": "right",
  "cvUrl": ""
},

  seo: {
  "title": "aziz said — Full Stack",
  "description": "Portfolio of aziz said — Full Stack",
  "ogTitle": "aziz said — Portfolio",
  "ogDescription": "Full Stack"
},

  navigation: [
    { label: "Expertise", targetId: "tiles" },
    { label: "Work", targetId: "projects" },
    { label: "About", targetId: "about" },
    { label: "Timeline", targetId: "experience" },
    ...[{"label":"Testimonials","targetId":"section-cs-1790879670065"}],
    { label: "Contact", targetId: "contact" },
  ] as NavItem[],

  marquee: ["python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react","python","react"],

  expertiseHeader: {
  "titleMain": "Core",
  "titleAccent": "Expertise",
  "badge": "2 Domains"
},

  expertise: [
  {
    "id": "tile-1790879392307",
    "num": "01",
    "name": "React",
    "desc": "React",
    "type": "dna"
  },
  {
    "id": "tile-1790879411423",
    "num": "02",
    "name": "Java",
    "desc": "Java",
    "type": "network"
  }
] as ExpertiseItem[],

  projectsHeader: {
  "titleMain": "Deployed",
  "titleAccent": "Systems"
},

  projects: [
  {
    "id": "pc-1790879426106",
    "num": "01 / 02",
    "cat": "Computer",
    "flip": false,
    "titlePrefix": "Ai",
    "titleHighlight": "AI",
    "titleSuffix": "Tracker",
    "img": "https://res.cloudinary.com/dhlnfpfen/image/upload/v1790879468/portfolio-assets/project-pc-1790879426106/mfkwapyrynnjnx1jdj4l.jpg",
    "desc": "hfbhabfkabkjbfka",
    "tech": [
      "Rect"
    ],
    "link": "https://github......."
  },
  {
    "id": "pc-1790879481325",
    "num": "02 / 02",
    "cat": "AU",
    "flip": true,
    "titlePrefix": "AU",
    "titleHighlight": "AU",
    "titleSuffix": "AU",
    "img": "https://res.cloudinary.com/dhlnfpfen/image/upload/v1790879496/portfolio-assets/project-pc-1790879481325/i6cib9nhkl1zdwwzquxt.jpg",
    "desc": "FNEJKZBB EKBK",
    "tech": [
      "React"
    ],
    "link": "AU"
  }
] as ProjectItem[],

  about: {
    ...{
  "statementLine1": "Building the",
  "statementHighlight": "intelligent",
  "statementLine2": "web, one",
  "statementLine3": "system at a time.",
  "paragraphs": [
    "BVHVBJBLZBVHBZJNV NCKZ EJBVBHJH EJHZE"
  ]
},
    stats: [
  {
    "n": "7.5",
    "l": "abbb"
  },
  {
    "n": "6.5",
    "l": "aa"
  }
] as StatItem[],
  },

  timeline: {
    ...{
  "titleMain": "Track",
  "titleAccent": "Record",
  "trainingColumnTitle": "Training & Certifications",
  "hackathonsColumnTitle": "Hackathons"
},
    training: [
  {
    "title": "AWS",
    "org": "AWS",
    "desc": "AWS",
    "active": true
  },
  {
    "title": "AWS",
    "org": "AWS",
    "desc": "AWS",
    "active": true
  }
] as TrainingItem[],
    hackathons: [
  {
    "name": "COPS",
    "date": "2026",
    "desc": "COPS"
  },
  {
    "name": "COPS",
    "date": "2027",
    "desc": "COPS"
  }
] as HackathonItem[],
  },

  contact: {
    ...{
  "label": "— Get in touch",
  "headingLine1": "Let's",
  "headingHighlight": "Build",
  "headingLine2": "Together",
  "email": "amir12.amir0011@gmail.com",
  "emailSubject": "Let's connect"
},
    socials: [
  {
    "label": "Github",
    "url": "hfzhuhfuhie"
  }
] as SocialLink[],
  },

  footer: {
  "author": "aziz said",
  "logo": "AS.",
  "credit": "Designed & Built by aziz said"
},

  customSections: [
  {
    "id": "cs-1790879670065",
    "type": "testimonials",
    "title": "Testimonials",
    "visible": true,
    "items": [
      {
        "id": "cs-1790879670065-item-0",
        "heading": "Alexandre Moreauebebbkzk",
        "subheading": "VP Engineering @ Nexus AI",
        "body": "An exceptional engineer with remarkable architectural rigor. Our real-time streaming infrastructure was deployed two weeks ahead of schedule with total reliability.",
        "url": "https://linkedin.com"
      },
      {
        "id": "cs-1790879670065-item-1",
        "heading": "Elena Rostova",
        "subheading": "Head of Product @ QuantumLabs",
        "body": "Rare product intuition coupled with complete mastery of 3D WebGL. The final delivery exceeded expectations and deeply impressed our investors.",
        "url": "https://linkedin.com"
      }
    ]
  }
] as CustomSection[],
};
